tap "homebrew/bundle"

tap "homebrew/core"
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "mas"
brew "neovim"
brew "ripgrep"

tap "homebrew/cask"
cask "docker"

tap "epk/epk"
cask "font-sf-mono-nerd-font"

mas "1Password", id: 443987910
mas "Things", id: 904280696

