#!/bin/bash

read -p "*** CAUTION: overwrite git/vim/zsh symlinks in your home directory? " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]
then
    DOTFILES_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

    # git
    ln -sfn $DOTFILES_ROOT/git/gitconfig ~/.gitconfig

    # vim
    ln -sfn $DOTFILES_ROOT/vim ~/.vim
    ln -sfn $DOTFILES_ROOT/vim/vimrc ~/.vimrc
    ln -sfn $DOTFILES_ROOT/vim/gvimrc ~/.gvimrc

    # zsh
    ln -sfn $DOTFILES_ROOT/zsh/zshenv ~/.zshenv
    ln -sfn $DOTFILES_ROOT/zsh/zshrc ~/.zshrc

    echo "All installed!"
fi
