set nocompatible

filetype off
call pathogen#infect()
filetype plugin indent on

" Swapfiles are stored in ~/.vim/backup
silent !mkdir ~/.vim > /dev/null 2>&1
silent !mkdir ~/.vim/backup > /dev/null 2>&1

set backup
set backupdir=~/.vim/backup,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim/backup,~/.tmp,~/tmp,/var/tmp,/tmp

set number
set ruler
set showcmd
syntax on

set encoding=utf-8

set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch

" Always show status bar
set laststatus=2

" Recognize certain file types as Ruby
au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru}   set ft=ruby

" Allow backspacing over everything
set backspace=indent,eol,start

" Allow shift-arrow key to work in MacVim
let macvim_hig_shift_movement = 1

:colorscheme ir_black

" Not desirable
let g:netrw_dirhistmax=0
