set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

" Appearance
Bundle 'mattgreen/vim-github-colorscheme'

" Language support
Bundle 'kchmck/vim-coffee-script'
Bundle 'vim-ruby/vim-ruby'
Bundle 'jnwhiteh/vim-golang'
Bundle 'plasticboy/vim-markdown'

" Library support
Bundle 'tpope/vim-rails'
Bundle 'tpope/vim-haml'

" Plugins
Bundle 'rking/ag.vim'
Bundle 'tpope/vim-eunuch'
Bundle 'scrooloose/nerdcommenter'
Bundle 'shemerey/vim-peepopen'
Bundle 'airblade/vim-rooter'
Bundle 'tmhedberg/matchit'

filetype plugin indent on

" Disable swap and backup files
set nobackup
set noswapfile

set number
set numberwidth=5

set ruler
set showcmd
syntax on

set encoding=utf-8

set nowrap
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set list
set listchars=tab:\ \ ,trail:·
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
set gdefault

autocmd Filetype c setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4
autocmd Filetype cpp setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4

" Always show status bar
set laststatus=2

" Recognize certain file types as Ruby
au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru}   set ft=ruby

" Allow backspacing over everything
set backspace=indent,eol,start

set t_Co=256
colorscheme github

" Not desirable
let g:netrw_dirhistmax=0

let mapleader=","

" Remove trailing whitespace on save
function! TrimWhiteSpace()
    let l:winview = winsaveview()
    %s/\s\+$//e
    call winrestview(l:winview)
endfunction

" Reload vimrc on edit
augroup reload_vimrc " {
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }

runtime macros/matchit.vim
