# Asynchronously compile zcompdump if changed
{
    zcompare() {
        if [[ -s ${1} && ( ! -s ${1}.zwc || ${1} -nt ${1}.zwc) ]]; then
            zcompile ${1}
        fi
    }

    zcompare "${ZDOTDIR:-$HOME}/.zcompdump"
} &!